<script setup>

defineProps({
    label: String,
});

</script>

<template>
    <div
        class="bg-card-dark-blue/30 backdrop-blur-md rounded-2xl py-6 px-8 shadow-2xl border border-white/10 mb-2 text-center">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" width="230"
            height="230" style="shape-rendering: auto; display: block; background: transparent;"
            xmlns:xlink="http://www.w3.org/1999/xlink" class="mx-auto">
            <g>
                <path stroke="none" fill="#b3f5d4" d="M21 50A29 29 0 0 0 79 50A29 32.2 0 0 1 21 50">
                    <animateTransform values="0 50 51.6;360 50 51.6" keyTimes="0;1" repeatCount="indefinite"
                        dur="0.36900369003690037s" type="rotate" attributeName="transform"></animateTransform>
                </path>
                <g></g>
            </g><!-- [ldio] generated by https://loading.io -->
        </svg>
        <p class="mt-2 font-jura font-bold text-white">{{ label }}</p>
    </div>
</template>