<script setup>
import { ServiceAPI } from '@/service/apiService';
import { useOfferStore } from '@/service/offerStore';
import { ref, watch } from 'vue';

const emit = defineEmits(['changePdf'], ['loadingPdf']);

const insurers = { "asirom": "Asirom", "allianz": "Allianz", "axeria": "Axeria", "generali": "Generali", "groupama": "Groupama", "hellas_autonom": "Hellas Autonom", "hellas_nextins": "Hellas Nextins", "omniasig": "Omniasig", "grawe": "Grawe", "eazy_insure": "Eazy Insure" }

const pdfUrl = ref('');

const offerStore = useOfferStore();

const onClickOffer = async (offerId, offerPrice) => {
    emit('loadingPdf', true);
    try {
        const offer = await ServiceAPI.fetchOfferPdf(offerId);
        const content = offer[0].content;

        offerStore.setOfferId(offerId);
        offerStore.setAmount(offerPrice);

        var url = 'data:application/pdf;base64,' + content;
        var blobUrl;
        fetch(url)
            .then(res => res.blob())
            .then(URL.createObjectURL)
            .then((ret) => { blobUrl = ret; return blobUrl; })
            .then((res) => pdfUrl.value = res);

        emit('loadingPdf', false);
    } catch (error) {
        emit('loadingPdf', false);
        return;
    }
}

watch(pdfUrl, (onNewPdf) => {
    emit('changePdf', onNewPdf);
})

defineProps({
    loading: Boolean,
    offers: Object,
});
</script>

<template>
    <div>
        <template v-if="loading">
            <div
                class="bg-medium-ocean/10 backdrop-blur-md rounded-2xl py-6 px-8 shadow-2xl border border-white/10 mb-2 text-center">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" width="230"
                    height="230" style="shape-rendering: auto; display: block; background: transparent;"
                    xmlns:xlink="http://www.w3.org/1999/xlink" class="mx-auto">
                    <g>
                        <path stroke="none" fill="#b3f5d4" d="M21 50A29 29 0 0 0 79 50A29 32.2 0 0 1 21 50">
                            <animateTransform values="0 50 51.6;360 50 51.6" keyTimes="0;1" repeatCount="indefinite"
                                dur="0.36900369003690037s" type="rotate" attributeName="transform"></animateTransform>
                        </path>
                        <g></g>
                    </g><!-- [ldio] generated by https://loading.io -->
                </svg>
                <p class="mt-2 font-jura font-bold text-white">Cautam oferte...</p>
            </div>
        </template>
        <template v-else>
            <div v-for="offer in offers"
                class="relative bg-gradient-to-br from-medium-ocean/15 via-medium-ocean/10 to-medium-ocean/5 font-jura backdrop-blur-xl rounded-3xl p-8 shadow-2xl border border-white/20 mb-8 hover:shadow-3xl hover:border-white/30 transition-all duration-300 group overflow-hidden">

                <!-- Decorative gradient overlay -->
                <div
                    class="absolute inset-0 bg-gradient-to-br from-transparent via-white/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500 rounded-3xl">
                </div>

                <div v-if="offer.error === true" class="relative z-10">
                    <div class="flex items-center mb-6">
                        <div v-if="offer.message && offer.message !== 'VALIDATION_ERROR'"
                            class="w-2 h-12 bg-red-500 rounded-full mr-4"></div>
                        <div v-else class="w-2 h-12 bg-yellow-300 rounded-full mr-4"></div>
                        <p class="text-5xl font-bold tracking-tight text-white">{{ insurers[offer.businessName] ||
                            insurers[offer.business] }}</p>
                    </div>

                    <div v-if="offer.message && offer.message !== 'VALIDATION_ERROR'"
                        class="bg-red-500/10 border border-red-500/30 rounded-xl p-4 backdrop-blur-sm">
                        <p class="text-red-400 font-medium tracking-tight">{{ offer.message }}</p>
                    </div>

                    <div v-else class="bg-yellow-500/10 border border-yellow-500/30 rounded-xl p-4 backdrop-blur-sm">
                        <p class="text-yellow-300 font-medium tracking-tight mb-3">Câmpuri necesare pentru acest
                            asigurător:</p>
                        <div class="space-y-2">
                            <div v-for="err in offer.data" class="flex items-center">
                                <div class="w-1.5 h-1.5 bg-yellow-300 rounded-full mr-3"></div>
                                <p class="font-medium tracking-tight text-white/90">{{ err[0] }}</p>
                            </div>
                        </div>
                    </div>
                </div>

                <div v-else class="relative z-10">
                    <!-- Header Section -->
                    <div class="flex sm:flex-row flex-col justify-between sm:items-center mb-8">
                        <div class="flex-1">
                            <div class="flex items-center mb-4">
                                <div class="w-2 h-12 bg-gradient-to-b from-light-blue to-blue-400 rounded-full mr-4">
                                </div>
                                <p class="text-5xl font-bold tracking-tight text-white leading-tight">
                                    {{ insurers[offer.businessName] || insurers[offer.business] }}
                                </p>
                            </div>

                            <div
                                class="flex items-center text-white/80 bg-white/5 rounded-lg px-3 py-2 w-fit backdrop-blur-sm border border-white/10">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                    stroke-width="1.5" stroke="currentColor" class="h-4 w-4 mr-2">
                                    <path stroke-linecap="round" stroke-linejoin="round"
                                        d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 0 1 2.25-2.25h13.5A2.25 2.25 0 0 1 21 7.5v11.25m-18 0A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75m-18 0v-7.5A2.25 2.25 0 0 1 5.25 9h13.5A2.25 2.25 0 0 1 21 11.25v7.5m-9-6h.008v.008H12v-.008ZM12 15h.008v.008H12V15Zm0 2.25h.008v.008H12v-.008ZM9.75 15h.008v.008H9.75V15Zm0 2.25h.008v.008H9.75v-.008ZM7.5 15h.008v.008H7.5V15Zm0 2.25h.008v.008H7.5v-.008Zm6.75-4.5h.008v.008h-.008v-.008Zm0 2.25h.008v.008h-.008V15Zm0 2.25h.008v.008h-.008v-.008Zm2.25-4.5h.008v.008H16.5v-.008Zm0 2.25h.008v.008H16.5V15Z" />
                                </svg>
                                <p class="text-sm font-medium tracking-tight">{{ offer.startDate }} - {{ offer.endDate
                                    }}</p>
                            </div>
                        </div>

                        <!-- Price Card -->
                        <div
                            class="bg-gradient-to-br sm:group-hover:backdrop-blur-xl rounded-2xl sm:p-6 sm:mt-0 mt-6 sm:group-hover:shadow-xl hover:border-white/30 transition-all duration-300 min-w-[180px]">
                            <div class="text-center">
                                <p class="text-2xl font-bold text-white mb-1">{{ offer.premiumAmount }} {{
                                    offer.currency }}</p>
                                <p class="text-xs text-white/60 font-medium mb-2">+ TVA</p>
                                <div
                                    class="w-full h-px bg-gradient-to-r from-transparent via-white/30 to-transparent mb-2">
                                </div>
                                <p class="text-sm text-white/80 font-medium">{{ offer.premiumAmountNet }} {{
                                    offer.currency }}</p>
                                <p class="text-xs text-white/50">fără TVA</p>
                            </div>
                        </div>
                    </div>

                    <!-- Details Section -->
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-8">
                        <div
                            class="flex items-center bg-white/5 rounded-xl px-4 py-3 backdrop-blur-sm border border-white/10 hover:bg-white/10 transition-all duration-300">
                            <div class="bg-gradient-to-br from-green-400 to-emerald-500 p-2 rounded-lg mr-3">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2"
                                    stroke="currentColor" class="h-4 w-4 text-white">
                                    <path stroke-linecap="round" stroke-linejoin="round"
                                        d="M2.25 18 9 11.25l4.306 4.306a11.95 11.95 0 0 1 5.814-5.518l2.74-1.22m0 0-5.94-2.281m5.94 2.28-2.28 5.941" />
                                </svg>
                            </div>
                            <div>
                                <p class="text-white font-semibold text-sm">Clasă Bonus</p>
                                <p class="text-white/70 text-xs">{{ offer.bonusMalusClass }}</p>
                            </div>
                        </div>

                        <div
                            class="flex items-center bg-white/5 rounded-xl px-4 py-3 backdrop-blur-sm border border-white/10 hover:bg-white/10 transition-all duration-300">
                            <div class="bg-gradient-to-br from-amber-400 to-orange-500 p-2 rounded-lg mr-3">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2"
                                    stroke="currentColor" class="h-4 w-4 text-white">
                                    <path stroke-linecap="round" stroke-linejoin="round"
                                        d="m9.75 9.75 4.5 4.5m0-4.5-4.5 4.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                                </svg>
                            </div>
                            <div>
                                <p class="text-white font-semibold text-sm">Green Card</p>
                                <p class="text-white/70 text-xs">Excluse: {{ offer.greenCardExclusions }}</p>
                            </div>
                        </div>
                    </div>

                    <!-- Action Button -->
                    <div class="flex flex-col items-center space-y-3">
                        <button @click="onClickOffer(offer.offerId, offer.premiumAmount)"
                            class="bg-transparent border-[1.2px] hover:bg-light-blue/10 border-light-blue/50 text-white font-jura font-semibold transition-all duration-200 rounded-lg py-3 px-[34px] shadow-lg hover:shadow-xl">
                            <!-- Button shine effect -->

                            <span class="relative z-10 flex items-center">
                                Vezi Oferta
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2"
                                    stroke="currentColor"
                                    class="h-5 w-5 ml-2 group-hover/btn:translate-x-1 transition-transform duration-300">
                                    <path stroke-linecap="round" stroke-linejoin="round"
                                        d="M13.5 4.5 21 12m0 0-7.5 7.5M21 12H3" />
                                </svg>
                            </span>
                        </button>

                        <!-- Expiry date -->
                        <div class="bg-white/5 rounded-lg px-4 py-2 backdrop-blur-sm border border-white/10">
                            <p class="text-center text-xs text-white/60 font-medium">
                                Ofertă valabilă până pe: <span class="text-white/80 font-semibold">{{
                                    offer.offerExpiryDate }}</span>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </template>
        <div class="flex justify-center">
            <button @click="$emit('go-back')"
                class="bg-red-500/30 border-[1.2px] hover:bg-red-500/50 border-red-600/20 text-white font-jura font-semibold transition-all duration-200 rounded py-3 px-[52px] shadow-lg hover:shadow-xl">
                Inapoi
            </button>
        </div>
    </div>
</template>
